name = "deepseek-chat-worker"
main = "src/index.js"
compatibility_date = "2024-03-01"

[build]


[vars]
# 加密配置
ENCRYPTION_ALGO = "AES-GCM"
ENCRYPTION_KEY_VERSION = "v1"

# KV存储配置
[[kv_namespaces]]
binding = "ENCRYPTED_STORAGE"
id = "df1a3dbe11df4fc4a04d58648f0b7b9d"
preview_id = "your_preview_id"

# 加密密钥（通过wrangler secret设置）
[secrets]
ENCRYPTION_KEY_BASE64 = "c6aad780c6dae2674bd5e897e2a82027"
ENCRYPTION_KEY = "sk-a96fce2c05e14d78bd5195534b211385"
