name = "deepseek-chat-worker"
main = "src/index.js"
compatibility_date = "2024-03-01"

[build]


[vars]
# 加密配置
ENCRYPTION_ALGO = "AES-GCM"
ENCRYPTION_KEY_VERSION = "v1"

# KV存储配置
[[kv_namespaces]]
binding = "ENCRYPTED_STORAGE"
id = "your_kv_namespace_id"
preview_id = "your_preview_id"

# 加密密钥（通过wrangler secret设置）
[secrets]
ENCRYPTION_KEY_BASE64 = "@encryption_key_base64"
